language: python
python:
- 2.7
- 3.6
before_install:
- sudo apt-get update
- sudo apt-get install -y openjdk-8-jdk
install:
- pip install --upgrade pip setuptools tox-travis virtualenv coveralls
script:
- tox -v
after_success: coveralls
notifications:
  email: false
deploy:
  provider: pypi
  user: netauto
  password:
    secure: Sk02tn1ouabQJIiRcYtKHWIjhuXgjXKJFCk3wIqctbqmIYnzvq82oB+1rZJnKa24j+1pUTHHHTU91vHhhSqO4sbqMiwmOsKImdPobJrVOCRN5tRyTfzFzgkp0tcZ9vQ10Evm7wqV0ip9X7A0++6lWiVY75doLfwEK007PnFTsOZmIyiambTXRCVLV4WtEOa8bJ++4sGQmfaVMIfEi+snzJ5ulKhtZyQK6KhXoosLK3UwAMfBYkP0jmtGorDVOcZUdtO0AoPiV5AHyzWXyDWQ1bJ6Gxu/PJZPHUVtGVB2kMTTlGg40TeEHXZG6+tk5oR192MUwNFDk6Z1LjNSiHCkCeebhLd4Ld7dpk2tt/ujGEXHFNnc3oOvkv7k5J8ehaNebDyWUDCceh0vvbrMi3yWSrBiUdEJWTYArZhHviQ2lvUMskTOtvSMX4EQRLs+1MHd4fIVWA4AMluzYTNNgl9tzpWASRl/cdxy4FBE8siDB8boG5WuB0CE7nU8UFGTcmiTe44+uSgDk1DTpsNVFKMI5qAqyksye4kn1TqwneDknbY0DlZLamBJhSselM1i5plfhwy0GxbItOmjwQDmT9cQJMUz0w/pYpGDmlOa3deen7mvnzduJfgkauU/w+XWjC25S81FhewEqe6qY2VURuQX1EN1LNguy5QwcfEHVdwyuW4=
  distributions: sdist
  on:
    tags: true
